using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjectMeowth.Models
{
    public class PokedexFakeGenerator
    {
        // THIS IS A TEMPORARY MEASURE TO POPULATE THE POKEDEX, UNTIL IT IS LINKED TO A DATABASE
        
        public List<PokemonModel> GetFakePokedex()
        {
            List<PokemonModel> lstPokemon = new List<PokemonModel>
            {
                new PokemonModel(Name: "Bulbasaur", SpeciesID: 1, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Grass"),
                new PokemonModel(Name: "Ivysaur", SpeciesID: 2, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Grass"),
                new PokemonModel(Name: "Venusaur", SpeciesID: 3, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Grass"),
                new PokemonModel(Name: "Charmander", SpeciesID: 4, Generation: 1, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Charmeleon", SpeciesID: 5, Generation: 1, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Charizard", SpeciesID: 6, Generation: 1, PokemonType: "PokemonType-Flying, PokemonType-Fire"),
                new PokemonModel(Name: "Squirtle", SpeciesID: 7, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Wartortle", SpeciesID: 8, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Blastoise", SpeciesID: 9, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Caterpie", SpeciesID: 10, Generation: 1, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Metapod", SpeciesID: 11, Generation: 1, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Butterfree", SpeciesID: 12, Generation: 1, PokemonType: "PokemonType-Flying, PokemonType-Bug"),
                new PokemonModel(Name: "Weedle", SpeciesID: 13, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Bug"),
                new PokemonModel(Name: "Kakuna", SpeciesID: 14, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Bug"),
                new PokemonModel(Name: "Beedrill", SpeciesID: 15, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Bug"),
                new PokemonModel(Name: "Pidgey", SpeciesID: 16, Generation: 1, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Pidgeotto", SpeciesID: 17, Generation: 1, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Pidgeot", SpeciesID: 18, Generation: 1, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Rattata", SpeciesID: 19, Generation: 1, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Raticate", SpeciesID: 20, Generation: 1, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Spearow", SpeciesID: 21, Generation: 1, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Fearow", SpeciesID: 22, Generation: 1, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Ekans", SpeciesID: 23, Generation: 1, PokemonType: "PokemonType-Poison"),
                new PokemonModel(Name: "Arbok", SpeciesID: 24, Generation: 1, PokemonType: "PokemonType-Poison"),
                new PokemonModel(Name: "Pikachu", SpeciesID: 25, Generation: 1, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Raichu", SpeciesID: 26, Generation: 1, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Sandshrew", SpeciesID: 27, Generation: 1, PokemonType: "PokemonType-Ground"),
                new PokemonModel(Name: "Sandslash", SpeciesID: 28, Generation: 1, PokemonType: "PokemonType-Ground"),
                new PokemonModel(Name: "Nidoran-f", SpeciesID: 29, Generation: 1, PokemonType: "PokemonType-Poison"),
                new PokemonModel(Name: "Nidorina", SpeciesID: 30, Generation: 1, PokemonType: "PokemonType-Poison"),
                new PokemonModel(Name: "Nidoqueen", SpeciesID: 31, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Ground"),
                new PokemonModel(Name: "Nidoran-m", SpeciesID: 32, Generation: 1, PokemonType: "PokemonType-Poison"),
                new PokemonModel(Name: "Nidorino", SpeciesID: 33, Generation: 1, PokemonType: "PokemonType-Poison"),
                new PokemonModel(Name: "Nidoking", SpeciesID: 34, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Ground"),
                new PokemonModel(Name: "Vulpix", SpeciesID: 37, Generation: 1, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Ninetales", SpeciesID: 38, Generation: 1, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Jigglypuff", SpeciesID: 39, Generation: 1, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Wigglytuff", SpeciesID: 40, Generation: 1, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Zubat", SpeciesID: 41, Generation: 1, PokemonType: "PokemonType-Flying, PokemonType-Poison"),
                new PokemonModel(Name: "Golbat", SpeciesID: 42, Generation: 1, PokemonType: "PokemonType-Flying, PokemonType-Poison"),
                new PokemonModel(Name: "Oddish", SpeciesID: 43, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Grass"),
                new PokemonModel(Name: "Gloom", SpeciesID: 44, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Grass"),
                new PokemonModel(Name: "Vileplume", SpeciesID: 45, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Grass"),
                new PokemonModel(Name: "Paras", SpeciesID: 46, Generation: 1, PokemonType: "PokemonType-Bug, PokemonType-Grass"),
                new PokemonModel(Name: "Parasect", SpeciesID: 47, Generation: 1, PokemonType: "PokemonType-Bug, PokemonType-Grass"),
                new PokemonModel(Name: "Venonat", SpeciesID: 48, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Bug"),
                new PokemonModel(Name: "Venomoth", SpeciesID: 49, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Bug"),
                new PokemonModel(Name: "Diglett", SpeciesID: 50, Generation: 1, PokemonType: "PokemonType-Ground"),
                new PokemonModel(Name: "Dugtrio", SpeciesID: 51, Generation: 1, PokemonType: "PokemonType-Ground"),
                new PokemonModel(Name: "Meowth", SpeciesID: 52, Generation: 1, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Persian", SpeciesID: 53, Generation: 1, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Psyduck", SpeciesID: 54, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Golduck", SpeciesID: 55, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Mankey", SpeciesID: 56, Generation: 1, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Primeape", SpeciesID: 57, Generation: 1, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Growlithe", SpeciesID: 58, Generation: 1, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Arcanine", SpeciesID: 59, Generation: 1, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Poliwag", SpeciesID: 60, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Poliwhirl", SpeciesID: 61, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Poliwrath", SpeciesID: 62, Generation: 1, PokemonType: "PokemonType-Fighting, PokemonType-Water"),
                new PokemonModel(Name: "Abra", SpeciesID: 63, Generation: 1, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Kadabra", SpeciesID: 64, Generation: 1, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Alakazam", SpeciesID: 65, Generation: 1, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Machop", SpeciesID: 66, Generation: 1, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Machoke", SpeciesID: 67, Generation: 1, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Machamp", SpeciesID: 68, Generation: 1, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Bellsprout", SpeciesID: 69, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Grass"),
                new PokemonModel(Name: "Weepinbell", SpeciesID: 70, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Grass"),
                new PokemonModel(Name: "Victreebel", SpeciesID: 71, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Grass"),
                new PokemonModel(Name: "Tentacool", SpeciesID: 72, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Water"),
                new PokemonModel(Name: "Tentacruel", SpeciesID: 73, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Water"),
                new PokemonModel(Name: "Geodude", SpeciesID: 74, Generation: 1, PokemonType: "PokemonType-Ground, PokemonType-Rock"),
                new PokemonModel(Name: "Graveler", SpeciesID: 75, Generation: 1, PokemonType: "PokemonType-Ground, PokemonType-Rock"),
                new PokemonModel(Name: "Golem", SpeciesID: 76, Generation: 1, PokemonType: "PokemonType-Ground, PokemonType-Rock"),
                new PokemonModel(Name: "Ponyta", SpeciesID: 77, Generation: 1, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Rapidash", SpeciesID: 78, Generation: 1, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Slowpoke", SpeciesID: 79, Generation: 1, PokemonType: "PokemonType-Water, PokemonType-Psychic"),
                new PokemonModel(Name: "Slowbro", SpeciesID: 80, Generation: 1, PokemonType: "PokemonType-Water, PokemonType-Psychic"),
                new PokemonModel(Name: "Magnemite", SpeciesID: 81, Generation: 1, PokemonType: "PokemonType-Steel, PokemonType-Electric"),
                new PokemonModel(Name: "Magneton", SpeciesID: 82, Generation: 1, PokemonType: "PokemonType-Steel, PokemonType-Electric"),
                new PokemonModel(Name: "Farfetchd", SpeciesID: 83, Generation: 1, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Doduo", SpeciesID: 84, Generation: 1, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Dodrio", SpeciesID: 85, Generation: 1, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Seel", SpeciesID: 86, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Dewgong", SpeciesID: 87, Generation: 1, PokemonType: "PokemonType-Water, PokemonType-Ice"),
                new PokemonModel(Name: "Grimer", SpeciesID: 88, Generation: 1, PokemonType: "PokemonType-Poison"),
                new PokemonModel(Name: "Muk", SpeciesID: 89, Generation: 1, PokemonType: "PokemonType-Poison"),
                new PokemonModel(Name: "Shellder", SpeciesID: 90, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Cloyster", SpeciesID: 91, Generation: 1, PokemonType: "PokemonType-Water, PokemonType-Ice"),
                new PokemonModel(Name: "Gastly", SpeciesID: 92, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Ghost"),
                new PokemonModel(Name: "Haunter", SpeciesID: 93, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Ghost"),
                new PokemonModel(Name: "Gengar", SpeciesID: 94, Generation: 1, PokemonType: "PokemonType-Poison, PokemonType-Ghost"),
                new PokemonModel(Name: "Onix", SpeciesID: 95, Generation: 1, PokemonType: "PokemonType-Ground, PokemonType-Rock"),
                new PokemonModel(Name: "Drowzee", SpeciesID: 96, Generation: 1, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Hypno", SpeciesID: 97, Generation: 1, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Krabby", SpeciesID: 98, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Kingler", SpeciesID: 99, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Voltorb", SpeciesID: 100, Generation: 1, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Electrode", SpeciesID: 101, Generation: 1, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Exeggcute", SpeciesID: 102, Generation: 1, PokemonType: "PokemonType-Grass, PokemonType-Psychic"),
                new PokemonModel(Name: "Exeggutor", SpeciesID: 103, Generation: 1, PokemonType: "PokemonType-Grass, PokemonType-Psychic"),
                new PokemonModel(Name: "Cubone", SpeciesID: 104, Generation: 1, PokemonType: "PokemonType-Ground"),
                new PokemonModel(Name: "Marowak", SpeciesID: 105, Generation: 1, PokemonType: "PokemonType-Ground"),
                new PokemonModel(Name: "Hitmonlee", SpeciesID: 106, Generation: 1, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Hitmonchan", SpeciesID: 107, Generation: 1, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Lickitung", SpeciesID: 108, Generation: 1, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Koffing", SpeciesID: 109, Generation: 1, PokemonType: "PokemonType-Poison"),
                new PokemonModel(Name: "Weezing", SpeciesID: 110, Generation: 1, PokemonType: "PokemonType-Poison"),
                new PokemonModel(Name: "Rhyhorn", SpeciesID: 111, Generation: 1, PokemonType: "PokemonType-Ground, PokemonType-Rock"),
                new PokemonModel(Name: "Rhydon", SpeciesID: 112, Generation: 1, PokemonType: "PokemonType-Ground, PokemonType-Rock"),
                new PokemonModel(Name: "Chansey", SpeciesID: 113, Generation: 1, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Tangela", SpeciesID: 114, Generation: 1, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Kangaskhan", SpeciesID: 115, Generation: 1, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Horsea", SpeciesID: 116, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Seadra", SpeciesID: 117, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Goldeen", SpeciesID: 118, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Seaking", SpeciesID: 119, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Staryu", SpeciesID: 120, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Starmie", SpeciesID: 121, Generation: 1, PokemonType: "PokemonType-Water, PokemonType-Psychic"),
                new PokemonModel(Name: "Mr-mime", SpeciesID: 122, Generation: 1, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Scyther", SpeciesID: 123, Generation: 1, PokemonType: "PokemonType-Flying, PokemonType-Bug"),
                new PokemonModel(Name: "Jynx", SpeciesID: 124, Generation: 1, PokemonType: "PokemonType-Psychic, PokemonType-Ice"),
                new PokemonModel(Name: "Electabuzz", SpeciesID: 125, Generation: 1, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Magmar", SpeciesID: 126, Generation: 1, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Pinsir", SpeciesID: 127, Generation: 1, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Tauros", SpeciesID: 128, Generation: 1, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Magikarp", SpeciesID: 129, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Gyarados", SpeciesID: 130, Generation: 1, PokemonType: "PokemonType-Flying, PokemonType-Water"),
                new PokemonModel(Name: "Lapras", SpeciesID: 131, Generation: 1, PokemonType: "PokemonType-Water, PokemonType-Ice"),
                new PokemonModel(Name: "Ditto", SpeciesID: 132, Generation: 1, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Eevee", SpeciesID: 133, Generation: 1, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Vaporeon", SpeciesID: 134, Generation: 1, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Jolteon", SpeciesID: 135, Generation: 1, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Flareon", SpeciesID: 136, Generation: 1, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Porygon", SpeciesID: 137, Generation: 1, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Omanyte", SpeciesID: 138, Generation: 1, PokemonType: "PokemonType-Rock, PokemonType-Water"),
                new PokemonModel(Name: "Omastar", SpeciesID: 139, Generation: 1, PokemonType: "PokemonType-Rock, PokemonType-Water"),
                new PokemonModel(Name: "Kabuto", SpeciesID: 140, Generation: 1, PokemonType: "PokemonType-Rock, PokemonType-Water"),
                new PokemonModel(Name: "Kabutops", SpeciesID: 141, Generation: 1, PokemonType: "PokemonType-Rock, PokemonType-Water"),
                new PokemonModel(Name: "Aerodactyl", SpeciesID: 142, Generation: 1, PokemonType: "PokemonType-Flying, PokemonType-Rock"),
                new PokemonModel(Name: "Snorlax", SpeciesID: 143, Generation: 1, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Articuno", SpeciesID: 144, Generation: 1, PokemonType: "PokemonType-Flying, PokemonType-Ice"),
                new PokemonModel(Name: "Zapdos", SpeciesID: 145, Generation: 1, PokemonType: "PokemonType-Flying, PokemonType-Electric"),
                new PokemonModel(Name: "Moltres", SpeciesID: 146, Generation: 1, PokemonType: "PokemonType-Flying, PokemonType-Fire"),
                new PokemonModel(Name: "Dratini", SpeciesID: 147, Generation: 1, PokemonType: "PokemonType-Dragon"),
                new PokemonModel(Name: "Dragonair", SpeciesID: 148, Generation: 1, PokemonType: "PokemonType-Dragon"),
                new PokemonModel(Name: "Dragonite", SpeciesID: 149, Generation: 1, PokemonType: "PokemonType-Flying, PokemonType-Dragon"),
                new PokemonModel(Name: "Mewtwo", SpeciesID: 150, Generation: 1, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Mew", SpeciesID: 151, Generation: 1, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Chikorita", SpeciesID: 152, Generation: 2, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Bayleef", SpeciesID: 153, Generation: 2, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Cyndaquil", SpeciesID: 155, Generation: 2, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Quilava", SpeciesID: 156, Generation: 2, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Typhlosion", SpeciesID: 157, Generation: 2, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Totodile", SpeciesID: 158, Generation: 2, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Croconaw", SpeciesID: 159, Generation: 2, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Feraligatr", SpeciesID: 160, Generation: 2, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Sentret", SpeciesID: 161, Generation: 2, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Furret", SpeciesID: 162, Generation: 2, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Hoothoot", SpeciesID: 163, Generation: 2, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Noctowl", SpeciesID: 164, Generation: 2, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Ledyba", SpeciesID: 165, Generation: 2, PokemonType: "PokemonType-Flying, PokemonType-Bug"),
                new PokemonModel(Name: "Ledian", SpeciesID: 166, Generation: 2, PokemonType: "PokemonType-Flying, PokemonType-Bug"),
                new PokemonModel(Name: "Spinarak", SpeciesID: 167, Generation: 2, PokemonType: "PokemonType-Poison, PokemonType-Bug"),
                new PokemonModel(Name: "Ariados", SpeciesID: 168, Generation: 2, PokemonType: "PokemonType-Poison, PokemonType-Bug"),
                new PokemonModel(Name: "Crobat", SpeciesID: 169, Generation: 2, PokemonType: "PokemonType-Flying, PokemonType-Poison"),
                new PokemonModel(Name: "Chinchou", SpeciesID: 170, Generation: 2, PokemonType: "PokemonType-Water, PokemonType-Electric"),
                new PokemonModel(Name: "Lanturn", SpeciesID: 171, Generation: 2, PokemonType: "PokemonType-Water, PokemonType-Electric"),
                new PokemonModel(Name: "Pichu", SpeciesID: 172, Generation: 2, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Igglybuff", SpeciesID: 174, Generation: 2, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Togetic", SpeciesID: 176, Generation: 2, PokemonType: "PokemonType-Flying"),
                new PokemonModel(Name: "Natu", SpeciesID: 177, Generation: 2, PokemonType: "PokemonType-Flying, PokemonType-Psychic"),
                new PokemonModel(Name: "Xatu", SpeciesID: 178, Generation: 2, PokemonType: "PokemonType-Flying, PokemonType-Psychic"),
                new PokemonModel(Name: "Mareep", SpeciesID: 179, Generation: 2, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Flaaffy", SpeciesID: 180, Generation: 2, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Ampharos", SpeciesID: 181, Generation: 2, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Bellossom", SpeciesID: 182, Generation: 2, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Marill", SpeciesID: 183, Generation: 2, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Azumarill", SpeciesID: 184, Generation: 2, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Sudowoodo", SpeciesID: 185, Generation: 2, PokemonType: "PokemonType-Rock"),
                new PokemonModel(Name: "Politoed", SpeciesID: 186, Generation: 2, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Hoppip", SpeciesID: 187, Generation: 2, PokemonType: "PokemonType-Flying, PokemonType-Grass"),
                new PokemonModel(Name: "Skiploom", SpeciesID: 188, Generation: 2, PokemonType: "PokemonType-Flying, PokemonType-Grass"),
                new PokemonModel(Name: "Jumpluff", SpeciesID: 189, Generation: 2, PokemonType: "PokemonType-Flying, PokemonType-Grass"),
                new PokemonModel(Name: "Aipom", SpeciesID: 190, Generation: 2, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Sunkern", SpeciesID: 191, Generation: 2, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Sunflora", SpeciesID: 192, Generation: 2, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Yanma", SpeciesID: 193, Generation: 2, PokemonType: "PokemonType-Flying, PokemonType-Bug"),
                new PokemonModel(Name: "Wooper", SpeciesID: 194, Generation: 2, PokemonType: "PokemonType-Ground, PokemonType-Water"),
                new PokemonModel(Name: "Quagsire", SpeciesID: 195, Generation: 2, PokemonType: "PokemonType-Ground, PokemonType-Water"),
                new PokemonModel(Name: "Espeon", SpeciesID: 196, Generation: 2, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Umbreon", SpeciesID: 197, Generation: 2, PokemonType: "PokemonType-Dark"),
                new PokemonModel(Name: "Murkrow", SpeciesID: 198, Generation: 2, PokemonType: "PokemonType-Flying, PokemonType-Dark"),
                new PokemonModel(Name: "Slowking", SpeciesID: 199, Generation: 2, PokemonType: "PokemonType-Water, PokemonType-Psychic"),
                new PokemonModel(Name: "Misdreavus", SpeciesID: 200, Generation: 2, PokemonType: "PokemonType-Ghost"),
                new PokemonModel(Name: "Unown", SpeciesID: 201, Generation: 2, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Wobbuffet", SpeciesID: 202, Generation: 2, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Girafarig", SpeciesID: 203, Generation: 2, PokemonType: "PokemonType-Normal, PokemonType-Psychic"),
                new PokemonModel(Name: "Pineco", SpeciesID: 204, Generation: 2, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Forretress", SpeciesID: 205, Generation: 2, PokemonType: "PokemonType-Bug, PokemonType-Steel"),
                new PokemonModel(Name: "Dunsparce", SpeciesID: 206, Generation: 2, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Gligar", SpeciesID: 207, Generation: 2, PokemonType: "PokemonType-Flying, PokemonType-Ground"),
                new PokemonModel(Name: "Steelix", SpeciesID: 208, Generation: 2, PokemonType: "PokemonType-Ground, PokemonType-Steel"),
                new PokemonModel(Name: "Qwilfish", SpeciesID: 211, Generation: 2, PokemonType: "PokemonType-Poison, PokemonType-Water"),
                new PokemonModel(Name: "Scizor", SpeciesID: 212, Generation: 2, PokemonType: "PokemonType-Bug, PokemonType-Steel"),
                new PokemonModel(Name: "Shuckle", SpeciesID: 213, Generation: 2, PokemonType: "PokemonType-Rock, PokemonType-Bug"),
                new PokemonModel(Name: "Heracross", SpeciesID: 214, Generation: 2, PokemonType: "PokemonType-Fighting, PokemonType-Bug"),
                new PokemonModel(Name: "Sneasel", SpeciesID: 215, Generation: 2, PokemonType: "PokemonType-Ice, PokemonType-Dark"),
                new PokemonModel(Name: "Teddiursa", SpeciesID: 216, Generation: 2, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Ursaring", SpeciesID: 217, Generation: 2, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Slugma", SpeciesID: 218, Generation: 2, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Magcargo", SpeciesID: 219, Generation: 2, PokemonType: "PokemonType-Rock, PokemonType-Fire"),
                new PokemonModel(Name: "Swinub", SpeciesID: 220, Generation: 2, PokemonType: "PokemonType-Ground, PokemonType-Ice"),
                new PokemonModel(Name: "Piloswine", SpeciesID: 221, Generation: 2, PokemonType: "PokemonType-Ground, PokemonType-Ice"),
                new PokemonModel(Name: "Corsola", SpeciesID: 222, Generation: 2, PokemonType: "PokemonType-Rock, PokemonType-Water"),
                new PokemonModel(Name: "Remoraid", SpeciesID: 223, Generation: 2, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Octillery", SpeciesID: 224, Generation: 2, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Delibird", SpeciesID: 225, Generation: 2, PokemonType: "PokemonType-Flying, PokemonType-Ice"),
                new PokemonModel(Name: "Mantine", SpeciesID: 226, Generation: 2, PokemonType: "PokemonType-Flying, PokemonType-Water"),
                new PokemonModel(Name: "Skarmory", SpeciesID: 227, Generation: 2, PokemonType: "PokemonType-Flying, PokemonType-Steel"),
                new PokemonModel(Name: "Houndour", SpeciesID: 228, Generation: 2, PokemonType: "PokemonType-Fire, PokemonType-Dark"),
                new PokemonModel(Name: "Houndoom", SpeciesID: 229, Generation: 2, PokemonType: "PokemonType-Fire, PokemonType-Dark"),
                new PokemonModel(Name: "Kingdra", SpeciesID: 230, Generation: 2, PokemonType: "PokemonType-Water, PokemonType-Dragon"),
                new PokemonModel(Name: "Phanpy", SpeciesID: 231, Generation: 2, PokemonType: "PokemonType-Ground"),
                new PokemonModel(Name: "Donphan", SpeciesID: 232, Generation: 2, PokemonType: "PokemonType-Ground"),
                new PokemonModel(Name: "Porygon2", SpeciesID: 233, Generation: 2, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Stantler", SpeciesID: 234, Generation: 2, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Smeargle", SpeciesID: 235, Generation: 2, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Tyrogue", SpeciesID: 236, Generation: 2, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Hitmontop", SpeciesID: 237, Generation: 2, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Smoochum", SpeciesID: 238, Generation: 2, PokemonType: "PokemonType-Psychic, PokemonType-Ice"),
                new PokemonModel(Name: "Elekid", SpeciesID: 239, Generation: 2, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Magby", SpeciesID: 240, Generation: 2, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Miltank", SpeciesID: 241, Generation: 2, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Blissey", SpeciesID: 242, Generation: 2, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Raikou", SpeciesID: 243, Generation: 2, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Entei", SpeciesID: 244, Generation: 2, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Suicune", SpeciesID: 245, Generation: 2, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Larvitar", SpeciesID: 246, Generation: 2, PokemonType: "PokemonType-Ground, PokemonType-Rock"),
                new PokemonModel(Name: "Pupitar", SpeciesID: 247, Generation: 2, PokemonType: "PokemonType-Ground, PokemonType-Rock"),
                new PokemonModel(Name: "Tyranitar", SpeciesID: 248, Generation: 2, PokemonType: "PokemonType-Rock, PokemonType-Dark"),
                new PokemonModel(Name: "Lugia", SpeciesID: 249, Generation: 2, PokemonType: "PokemonType-Flying, PokemonType-Psychic"),
                new PokemonModel(Name: "Ho-oh", SpeciesID: 250, Generation: 2, PokemonType: "PokemonType-Flying, PokemonType-Fire"),
                new PokemonModel(Name: "Celebi", SpeciesID: 251, Generation: 2, PokemonType: "PokemonType-Grass, PokemonType-Psychic"),
                new PokemonModel(Name: "Treecko", SpeciesID: 252, Generation: 3, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Grovyle", SpeciesID: 253, Generation: 3, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Sceptile", SpeciesID: 254, Generation: 3, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Torchic", SpeciesID: 255, Generation: 3, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Combusken", SpeciesID: 256, Generation: 3, PokemonType: "PokemonType-Fighting, PokemonType-Fire"),
                new PokemonModel(Name: "Blaziken", SpeciesID: 257, Generation: 3, PokemonType: "PokemonType-Fighting, PokemonType-Fire"),
                new PokemonModel(Name: "Mudkip", SpeciesID: 258, Generation: 3, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Marshtomp", SpeciesID: 259, Generation: 3, PokemonType: "PokemonType-Ground, PokemonType-Water"),
                new PokemonModel(Name: "Swampert", SpeciesID: 260, Generation: 3, PokemonType: "PokemonType-Ground, PokemonType-Water"),
                new PokemonModel(Name: "Poochyena", SpeciesID: 261, Generation: 3, PokemonType: "PokemonType-Dark"),
                new PokemonModel(Name: "Mightyena", SpeciesID: 262, Generation: 3, PokemonType: "PokemonType-Dark"),
                new PokemonModel(Name: "Zigzagoon", SpeciesID: 263, Generation: 3, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Linoone", SpeciesID: 264, Generation: 3, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Wurmple", SpeciesID: 265, Generation: 3, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Silcoon", SpeciesID: 266, Generation: 3, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Beautifly", SpeciesID: 267, Generation: 3, PokemonType: "PokemonType-Flying, PokemonType-Bug"),
                new PokemonModel(Name: "Cascoon", SpeciesID: 268, Generation: 3, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Dustox", SpeciesID: 269, Generation: 3, PokemonType: "PokemonType-Poison, PokemonType-Bug"),
                new PokemonModel(Name: "Lotad", SpeciesID: 270, Generation: 3, PokemonType: "PokemonType-Water, PokemonType-Grass"),
                new PokemonModel(Name: "Lombre", SpeciesID: 271, Generation: 3, PokemonType: "PokemonType-Water, PokemonType-Grass"),
                new PokemonModel(Name: "Ludicolo", SpeciesID: 272, Generation: 3, PokemonType: "PokemonType-Water, PokemonType-Grass"),
                new PokemonModel(Name: "Seedot", SpeciesID: 273, Generation: 3, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Nuzleaf", SpeciesID: 274, Generation: 3, PokemonType: "PokemonType-Grass, PokemonType-Dark"),
                new PokemonModel(Name: "Shiftry", SpeciesID: 275, Generation: 3, PokemonType: "PokemonType-Grass, PokemonType-Dark"),
                new PokemonModel(Name: "Taillow", SpeciesID: 276, Generation: 3, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Swellow", SpeciesID: 277, Generation: 3, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Wingull", SpeciesID: 278, Generation: 3, PokemonType: "PokemonType-Flying, PokemonType-Water"),
                new PokemonModel(Name: "Pelipper", SpeciesID: 279, Generation: 3, PokemonType: "PokemonType-Flying, PokemonType-Water"),
                new PokemonModel(Name: "Ralts", SpeciesID: 280, Generation: 3, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Kirlia", SpeciesID: 281, Generation: 3, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Gardevoir", SpeciesID: 282, Generation: 3, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Surskit", SpeciesID: 283, Generation: 3, PokemonType: "PokemonType-Bug, PokemonType-Water"),
                new PokemonModel(Name: "Masquerain", SpeciesID: 284, Generation: 3, PokemonType: "PokemonType-Flying, PokemonType-Bug"),
                new PokemonModel(Name: "Shroomish", SpeciesID: 285, Generation: 3, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Breloom", SpeciesID: 286, Generation: 3, PokemonType: "PokemonType-Fighting, PokemonType-Grass"),
                new PokemonModel(Name: "Slakoth", SpeciesID: 287, Generation: 3, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Vigoroth", SpeciesID: 288, Generation: 3, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Slaking", SpeciesID: 289, Generation: 3, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Nincada", SpeciesID: 290, Generation: 3, PokemonType: "PokemonType-Ground, PokemonType-Bug"),
                new PokemonModel(Name: "Ninjask", SpeciesID: 291, Generation: 3, PokemonType: "PokemonType-Flying, PokemonType-Bug"),
                new PokemonModel(Name: "Shedinja", SpeciesID: 292, Generation: 3, PokemonType: "PokemonType-Bug, PokemonType-Ghost"),
                new PokemonModel(Name: "Whismur", SpeciesID: 293, Generation: 3, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Loudred", SpeciesID: 294, Generation: 3, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Exploud", SpeciesID: 295, Generation: 3, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Makuhita", SpeciesID: 296, Generation: 3, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Hariyama", SpeciesID: 297, Generation: 3, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Azurill", SpeciesID: 298, Generation: 3, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Nosepass", SpeciesID: 299, Generation: 3, PokemonType: "PokemonType-Rock"),
                new PokemonModel(Name: "Skitty", SpeciesID: 300, Generation: 3, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Delcatty", SpeciesID: 301, Generation: 3, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Sableye", SpeciesID: 302, Generation: 3, PokemonType: "PokemonType-Ghost, PokemonType-Dark"),
                new PokemonModel(Name: "Mawile", SpeciesID: 303, Generation: 3, PokemonType: "PokemonType-Steel"),
                new PokemonModel(Name: "Aron", SpeciesID: 304, Generation: 3, PokemonType: "PokemonType-Rock, PokemonType-Steel"),
                new PokemonModel(Name: "Lairon", SpeciesID: 305, Generation: 3, PokemonType: "PokemonType-Rock, PokemonType-Steel"),
                new PokemonModel(Name: "Aggron", SpeciesID: 306, Generation: 3, PokemonType: "PokemonType-Rock, PokemonType-Steel"),
                new PokemonModel(Name: "Meditite", SpeciesID: 307, Generation: 3, PokemonType: "PokemonType-Fighting, PokemonType-Psychic"),
                new PokemonModel(Name: "Medicham", SpeciesID: 308, Generation: 3, PokemonType: "PokemonType-Fighting, PokemonType-Psychic"),
                new PokemonModel(Name: "Electrike", SpeciesID: 309, Generation: 3, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Manectric", SpeciesID: 310, Generation: 3, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Plusle", SpeciesID: 311, Generation: 3, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Minun", SpeciesID: 312, Generation: 3, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Volbeat", SpeciesID: 313, Generation: 3, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Illumise", SpeciesID: 314, Generation: 3, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Roselia", SpeciesID: 315, Generation: 3, PokemonType: "PokemonType-Poison, PokemonType-Grass"),
                new PokemonModel(Name: "Gulpin", SpeciesID: 316, Generation: 3, PokemonType: "PokemonType-Poison"),
                new PokemonModel(Name: "Swalot", SpeciesID: 317, Generation: 3, PokemonType: "PokemonType-Poison"),
                new PokemonModel(Name: "Carvanha", SpeciesID: 318, Generation: 3, PokemonType: "PokemonType-Water, PokemonType-Dark"),
                new PokemonModel(Name: "Sharpedo", SpeciesID: 319, Generation: 3, PokemonType: "PokemonType-Water, PokemonType-Dark"),
                new PokemonModel(Name: "Wailmer", SpeciesID: 320, Generation: 3, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Wailord", SpeciesID: 321, Generation: 3, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Numel", SpeciesID: 322, Generation: 3, PokemonType: "PokemonType-Ground, PokemonType-Fire"),
                new PokemonModel(Name: "Camerupt", SpeciesID: 323, Generation: 3, PokemonType: "PokemonType-Ground, PokemonType-Fire"),
                new PokemonModel(Name: "Torkoal", SpeciesID: 324, Generation: 3, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Spoink", SpeciesID: 325, Generation: 3, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Grumpig", SpeciesID: 326, Generation: 3, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Spinda", SpeciesID: 327, Generation: 3, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Trapinch", SpeciesID: 328, Generation: 3, PokemonType: "PokemonType-Ground"),
                new PokemonModel(Name: "Vibrava", SpeciesID: 329, Generation: 3, PokemonType: "PokemonType-Ground, PokemonType-Dragon"),
                new PokemonModel(Name: "Flygon", SpeciesID: 330, Generation: 3, PokemonType: "PokemonType-Ground, PokemonType-Dragon"),
                new PokemonModel(Name: "Cacnea", SpeciesID: 331, Generation: 3, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Cacturne", SpeciesID: 332, Generation: 3, PokemonType: "PokemonType-Grass, PokemonType-Dark"),
                new PokemonModel(Name: "Swablu", SpeciesID: 333, Generation: 3, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Altaria", SpeciesID: 334, Generation: 3, PokemonType: "PokemonType-Flying, PokemonType-Dragon"),
                new PokemonModel(Name: "Zangoose", SpeciesID: 335, Generation: 3, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Seviper", SpeciesID: 336, Generation: 3, PokemonType: "PokemonType-Poison"),
                new PokemonModel(Name: "Lunatone", SpeciesID: 337, Generation: 3, PokemonType: "PokemonType-Rock, PokemonType-Psychic"),
                new PokemonModel(Name: "Solrock", SpeciesID: 338, Generation: 3, PokemonType: "PokemonType-Rock, PokemonType-Psychic"),
                new PokemonModel(Name: "Barboach", SpeciesID: 339, Generation: 3, PokemonType: "PokemonType-Ground, PokemonType-Water"),
                new PokemonModel(Name: "Whiscash", SpeciesID: 340, Generation: 3, PokemonType: "PokemonType-Ground, PokemonType-Water"),
                new PokemonModel(Name: "Corphish", SpeciesID: 341, Generation: 3, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Crawdaunt", SpeciesID: 342, Generation: 3, PokemonType: "PokemonType-Water, PokemonType-Dark"),
                new PokemonModel(Name: "Baltoy", SpeciesID: 343, Generation: 3, PokemonType: "PokemonType-Ground, PokemonType-Psychic"),
                new PokemonModel(Name: "Claydol", SpeciesID: 344, Generation: 3, PokemonType: "PokemonType-Ground, PokemonType-Psychic"),
                new PokemonModel(Name: "Lileep", SpeciesID: 345, Generation: 3, PokemonType: "PokemonType-Rock, PokemonType-Grass"),
                new PokemonModel(Name: "Cradily", SpeciesID: 346, Generation: 3, PokemonType: "PokemonType-Rock, PokemonType-Grass"),
                new PokemonModel(Name: "Anorith", SpeciesID: 347, Generation: 3, PokemonType: "PokemonType-Rock, PokemonType-Bug"),
                new PokemonModel(Name: "Armaldo", SpeciesID: 348, Generation: 3, PokemonType: "PokemonType-Rock, PokemonType-Bug"),
                new PokemonModel(Name: "Feebas", SpeciesID: 349, Generation: 3, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Milotic", SpeciesID: 350, Generation: 3, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Castform", SpeciesID: 351, Generation: 3, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Kecleon", SpeciesID: 352, Generation: 3, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Shuppet", SpeciesID: 353, Generation: 3, PokemonType: "PokemonType-Ghost"),
                new PokemonModel(Name: "Banette", SpeciesID: 354, Generation: 3, PokemonType: "PokemonType-Ghost"),
                new PokemonModel(Name: "Duskull", SpeciesID: 355, Generation: 3, PokemonType: "PokemonType-Ghost"),
                new PokemonModel(Name: "Dusclops", SpeciesID: 356, Generation: 3, PokemonType: "PokemonType-Ghost"),
                new PokemonModel(Name: "Tropius", SpeciesID: 357, Generation: 3, PokemonType: "PokemonType-Flying, PokemonType-Grass"),
                new PokemonModel(Name: "Chimecho", SpeciesID: 358, Generation: 3, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Absol", SpeciesID: 359, Generation: 3, PokemonType: "PokemonType-Dark"),
                new PokemonModel(Name: "Wynaut", SpeciesID: 360, Generation: 3, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Snorunt", SpeciesID: 361, Generation: 3, PokemonType: "PokemonType-Ice"),
                new PokemonModel(Name: "Glalie", SpeciesID: 362, Generation: 3, PokemonType: "PokemonType-Ice"),
                new PokemonModel(Name: "Spheal", SpeciesID: 363, Generation: 3, PokemonType: "PokemonType-Water, PokemonType-Ice"),
                new PokemonModel(Name: "Sealeo", SpeciesID: 364, Generation: 3, PokemonType: "PokemonType-Water, PokemonType-Ice"),
                new PokemonModel(Name: "Walrein", SpeciesID: 365, Generation: 3, PokemonType: "PokemonType-Water, PokemonType-Ice"),
                new PokemonModel(Name: "Clamperl", SpeciesID: 366, Generation: 3, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Huntail", SpeciesID: 367, Generation: 3, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Gorebyss", SpeciesID: 368, Generation: 3, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Relicanth", SpeciesID: 369, Generation: 3, PokemonType: "PokemonType-Rock, PokemonType-Water"),
                new PokemonModel(Name: "Luvdisc", SpeciesID: 370, Generation: 3, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Bagon", SpeciesID: 371, Generation: 3, PokemonType: "PokemonType-Dragon"),
                new PokemonModel(Name: "Shelgon", SpeciesID: 372, Generation: 3, PokemonType: "PokemonType-Dragon"),
                new PokemonModel(Name: "Salamence", SpeciesID: 373, Generation: 3, PokemonType: "PokemonType-Flying, PokemonType-Dragon"),
                new PokemonModel(Name: "Beldum", SpeciesID: 374, Generation: 3, PokemonType: "PokemonType-Steel, PokemonType-Psychic"),
                new PokemonModel(Name: "Metang", SpeciesID: 375, Generation: 3, PokemonType: "PokemonType-Steel, PokemonType-Psychic"),
                new PokemonModel(Name: "Metagross", SpeciesID: 376, Generation: 3, PokemonType: "PokemonType-Steel, PokemonType-Psychic"),
                new PokemonModel(Name: "Regirock", SpeciesID: 377, Generation: 3, PokemonType: "PokemonType-Rock"),
                new PokemonModel(Name: "Regice", SpeciesID: 378, Generation: 3, PokemonType: "PokemonType-Ice"),
                new PokemonModel(Name: "Registeel", SpeciesID: 379, Generation: 3, PokemonType: "PokemonType-Steel"),
                new PokemonModel(Name: "Latias", SpeciesID: 380, Generation: 3, PokemonType: "PokemonType-Psychic, PokemonType-Dragon"),
                new PokemonModel(Name: "Latios", SpeciesID: 381, Generation: 3, PokemonType: "PokemonType-Psychic, PokemonType-Dragon"),
                new PokemonModel(Name: "Kyogre", SpeciesID: 382, Generation: 3, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Groudon", SpeciesID: 383, Generation: 3, PokemonType: "PokemonType-Ground"),
                new PokemonModel(Name: "Rayquaza", SpeciesID: 384, Generation: 3, PokemonType: "PokemonType-Flying, PokemonType-Dragon"),
                new PokemonModel(Name: "Jirachi", SpeciesID: 385, Generation: 3, PokemonType: "PokemonType-Steel, PokemonType-Psychic"),
                new PokemonModel(Name: "Deoxys-normal", SpeciesID: 386, Generation: 3, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Turtwig", SpeciesID: 387, Generation: 4, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Grotle", SpeciesID: 388, Generation: 4, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Torterra", SpeciesID: 389, Generation: 4, PokemonType: "PokemonType-Ground, PokemonType-Grass"),
                new PokemonModel(Name: "Chimchar", SpeciesID: 390, Generation: 4, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Monferno", SpeciesID: 391, Generation: 4, PokemonType: "PokemonType-Fighting, PokemonType-Fire"),
                new PokemonModel(Name: "Infernape", SpeciesID: 392, Generation: 4, PokemonType: "PokemonType-Fighting, PokemonType-Fire"),
                new PokemonModel(Name: "Piplup", SpeciesID: 393, Generation: 4, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Prinplup", SpeciesID: 394, Generation: 4, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Empoleon", SpeciesID: 395, Generation: 4, PokemonType: "PokemonType-Steel, PokemonType-Water"),
                new PokemonModel(Name: "Starly", SpeciesID: 396, Generation: 4, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Staravia", SpeciesID: 397, Generation: 4, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Staraptor", SpeciesID: 398, Generation: 4, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Bidoof", SpeciesID: 399, Generation: 4, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Bibarel", SpeciesID: 400, Generation: 4, PokemonType: "PokemonType-Normal, PokemonType-Water"),
                new PokemonModel(Name: "Kricketot", SpeciesID: 401, Generation: 4, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Kricketune", SpeciesID: 402, Generation: 4, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Shinx", SpeciesID: 403, Generation: 4, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Luxio", SpeciesID: 404, Generation: 4, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Luxray", SpeciesID: 405, Generation: 4, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Budew", SpeciesID: 406, Generation: 4, PokemonType: "PokemonType-Poison, PokemonType-Grass"),
                new PokemonModel(Name: "Roserade", SpeciesID: 407, Generation: 4, PokemonType: "PokemonType-Poison, PokemonType-Grass"),
                new PokemonModel(Name: "Cranidos", SpeciesID: 408, Generation: 4, PokemonType: "PokemonType-Rock"),
                new PokemonModel(Name: "Rampardos", SpeciesID: 409, Generation: 4, PokemonType: "PokemonType-Rock"),
                new PokemonModel(Name: "Shieldon", SpeciesID: 410, Generation: 4, PokemonType: "PokemonType-Rock, PokemonType-Steel"),
                new PokemonModel(Name: "Bastiodon", SpeciesID: 411, Generation: 4, PokemonType: "PokemonType-Rock, PokemonType-Steel"),
                new PokemonModel(Name: "Burmy", SpeciesID: 412, Generation: 4, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Wormadam-plant", SpeciesID: 413, Generation: 4, PokemonType: "PokemonType-Bug, PokemonType-Grass"),
                new PokemonModel(Name: "Mothim", SpeciesID: 414, Generation: 4, PokemonType: "PokemonType-Flying, PokemonType-Bug"),
                new PokemonModel(Name: "Combee", SpeciesID: 415, Generation: 4, PokemonType: "PokemonType-Flying, PokemonType-Bug"),
                new PokemonModel(Name: "Vespiquen", SpeciesID: 416, Generation: 4, PokemonType: "PokemonType-Flying, PokemonType-Bug"),
                new PokemonModel(Name: "Pachirisu", SpeciesID: 417, Generation: 4, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Buizel", SpeciesID: 418, Generation: 4, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Floatzel", SpeciesID: 419, Generation: 4, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Cherubi", SpeciesID: 420, Generation: 4, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Cherrim", SpeciesID: 421, Generation: 4, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Shellos", SpeciesID: 422, Generation: 4, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Gastrodon", SpeciesID: 423, Generation: 4, PokemonType: "PokemonType-Ground, PokemonType-Water"),
                new PokemonModel(Name: "Ambipom", SpeciesID: 424, Generation: 4, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Drifloon", SpeciesID: 425, Generation: 4, PokemonType: "PokemonType-Flying, PokemonType-Ghost"),
                new PokemonModel(Name: "Drifblim", SpeciesID: 426, Generation: 4, PokemonType: "PokemonType-Flying, PokemonType-Ghost"),
                new PokemonModel(Name: "Buneary", SpeciesID: 427, Generation: 4, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Lopunny", SpeciesID: 428, Generation: 4, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Mismagius", SpeciesID: 429, Generation: 4, PokemonType: "PokemonType-Ghost"),
                new PokemonModel(Name: "Honchkrow", SpeciesID: 430, Generation: 4, PokemonType: "PokemonType-Flying, PokemonType-Dark"),
                new PokemonModel(Name: "Glameow", SpeciesID: 431, Generation: 4, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Purugly", SpeciesID: 432, Generation: 4, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Chingling", SpeciesID: 433, Generation: 4, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Stunky", SpeciesID: 434, Generation: 4, PokemonType: "PokemonType-Poison, PokemonType-Dark"),
                new PokemonModel(Name: "Skuntank", SpeciesID: 435, Generation: 4, PokemonType: "PokemonType-Poison, PokemonType-Dark"),
                new PokemonModel(Name: "Bronzor", SpeciesID: 436, Generation: 4, PokemonType: "PokemonType-Steel, PokemonType-Psychic"),
                new PokemonModel(Name: "Bronzong", SpeciesID: 437, Generation: 4, PokemonType: "PokemonType-Steel, PokemonType-Psychic"),
                new PokemonModel(Name: "Bonsly", SpeciesID: 438, Generation: 4, PokemonType: "PokemonType-Rock"),
                new PokemonModel(Name: "Mime-jr", SpeciesID: 439, Generation: 4, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Happiny", SpeciesID: 440, Generation: 4, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Chatot", SpeciesID: 441, Generation: 4, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Spiritomb", SpeciesID: 442, Generation: 4, PokemonType: "PokemonType-Ghost, PokemonType-Dark"),
                new PokemonModel(Name: "Gible", SpeciesID: 443, Generation: 4, PokemonType: "PokemonType-Ground, PokemonType-Dragon"),
                new PokemonModel(Name: "Gabite", SpeciesID: 444, Generation: 4, PokemonType: "PokemonType-Ground, PokemonType-Dragon"),
                new PokemonModel(Name: "Garchomp", SpeciesID: 445, Generation: 4, PokemonType: "PokemonType-Ground, PokemonType-Dragon"),
                new PokemonModel(Name: "Munchlax", SpeciesID: 446, Generation: 4, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Riolu", SpeciesID: 447, Generation: 4, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Lucario", SpeciesID: 448, Generation: 4, PokemonType: "PokemonType-Fighting, PokemonType-Steel"),
                new PokemonModel(Name: "Hippopotas", SpeciesID: 449, Generation: 4, PokemonType: "PokemonType-Ground"),
                new PokemonModel(Name: "Hippowdon", SpeciesID: 450, Generation: 4, PokemonType: "PokemonType-Ground"),
                new PokemonModel(Name: "Skorupi", SpeciesID: 451, Generation: 4, PokemonType: "PokemonType-Poison, PokemonType-Bug"),
                new PokemonModel(Name: "Drapion", SpeciesID: 452, Generation: 4, PokemonType: "PokemonType-Poison, PokemonType-Dark"),
                new PokemonModel(Name: "Croagunk", SpeciesID: 453, Generation: 4, PokemonType: "PokemonType-Fighting, PokemonType-Poison"),
                new PokemonModel(Name: "Toxicroak", SpeciesID: 454, Generation: 4, PokemonType: "PokemonType-Fighting, PokemonType-Poison"),
                new PokemonModel(Name: "Carnivine", SpeciesID: 455, Generation: 4, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Finneon", SpeciesID: 456, Generation: 4, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Lumineon", SpeciesID: 457, Generation: 4, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Mantyke", SpeciesID: 458, Generation: 4, PokemonType: "PokemonType-Flying, PokemonType-Water"),
                new PokemonModel(Name: "Snover", SpeciesID: 459, Generation: 4, PokemonType: "PokemonType-Grass, PokemonType-Ice"),
                new PokemonModel(Name: "Abomasnow", SpeciesID: 460, Generation: 4, PokemonType: "PokemonType-Grass, PokemonType-Ice"),
                new PokemonModel(Name: "Weavile", SpeciesID: 461, Generation: 4, PokemonType: "PokemonType-Ice, PokemonType-Dark"),
                new PokemonModel(Name: "Magnezone", SpeciesID: 462, Generation: 4, PokemonType: "PokemonType-Steel, PokemonType-Electric"),
                new PokemonModel(Name: "Lickilicky", SpeciesID: 463, Generation: 4, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Rhyperior", SpeciesID: 464, Generation: 4, PokemonType: "PokemonType-Ground, PokemonType-Rock"),
                new PokemonModel(Name: "Tangrowth", SpeciesID: 465, Generation: 4, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Electivire", SpeciesID: 466, Generation: 4, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Magmortar", SpeciesID: 467, Generation: 4, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Togekiss", SpeciesID: 468, Generation: 4, PokemonType: "PokemonType-Flying"),
                new PokemonModel(Name: "Leafeon", SpeciesID: 470, Generation: 4, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Glaceon", SpeciesID: 471, Generation: 4, PokemonType: "PokemonType-Ice"),
                new PokemonModel(Name: "Gliscor", SpeciesID: 472, Generation: 4, PokemonType: "PokemonType-Flying, PokemonType-Ground"),
                new PokemonModel(Name: "Mamoswine", SpeciesID: 473, Generation: 4, PokemonType: "PokemonType-Ground, PokemonType-Ice"),
                new PokemonModel(Name: "Porygon-z", SpeciesID: 474, Generation: 4, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Gallade", SpeciesID: 475, Generation: 4, PokemonType: "PokemonType-Fighting, PokemonType-Psychic"),
                new PokemonModel(Name: "Probopass", SpeciesID: 476, Generation: 4, PokemonType: "PokemonType-Rock, PokemonType-Steel"),
                new PokemonModel(Name: "Dusknoir", SpeciesID: 477, Generation: 4, PokemonType: "PokemonType-Ghost"),
                new PokemonModel(Name: "Froslass", SpeciesID: 478, Generation: 4, PokemonType: "PokemonType-Ghost, PokemonType-Ice"),
                new PokemonModel(Name: "Rotom", SpeciesID: 479, Generation: 4, PokemonType: "PokemonType-Ghost, PokemonType-Electric"),
                new PokemonModel(Name: "Uxie", SpeciesID: 480, Generation: 4, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Mesprit", SpeciesID: 481, Generation: 4, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Azelf", SpeciesID: 482, Generation: 4, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Dialga", SpeciesID: 483, Generation: 4, PokemonType: "PokemonType-Steel, PokemonType-Dragon"),
                new PokemonModel(Name: "Palkia", SpeciesID: 484, Generation: 4, PokemonType: "PokemonType-Water, PokemonType-Dragon"),
                new PokemonModel(Name: "Heatran", SpeciesID: 485, Generation: 4, PokemonType: "PokemonType-Steel, PokemonType-Fire"),
                new PokemonModel(Name: "Regigigas", SpeciesID: 486, Generation: 4, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Giratina-altered", SpeciesID: 487, Generation: 4, PokemonType: "PokemonType-Ghost, PokemonType-Dragon"),
                new PokemonModel(Name: "Cresselia", SpeciesID: 488, Generation: 4, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Phione", SpeciesID: 489, Generation: 4, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Manaphy", SpeciesID: 490, Generation: 4, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Darkrai", SpeciesID: 491, Generation: 4, PokemonType: "PokemonType-Dark"),
                new PokemonModel(Name: "Shaymin-land", SpeciesID: 492, Generation: 4, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Arceus", SpeciesID: 493, Generation: 4, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Victini", SpeciesID: 494, Generation: 5, PokemonType: "PokemonType-Fire, PokemonType-Psychic"),
                new PokemonModel(Name: "Snivy", SpeciesID: 495, Generation: 5, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Servine", SpeciesID: 496, Generation: 5, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Serperior", SpeciesID: 497, Generation: 5, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Tepig", SpeciesID: 498, Generation: 5, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Pignite", SpeciesID: 499, Generation: 5, PokemonType: "PokemonType-Fighting, PokemonType-Fire"),
                new PokemonModel(Name: "Emboar", SpeciesID: 500, Generation: 5, PokemonType: "PokemonType-Fighting, PokemonType-Fire"),
                new PokemonModel(Name: "Oshawott", SpeciesID: 501, Generation: 5, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Dewott", SpeciesID: 502, Generation: 5, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Samurott", SpeciesID: 503, Generation: 5, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Patrat", SpeciesID: 504, Generation: 5, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Watchog", SpeciesID: 505, Generation: 5, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Lillipup", SpeciesID: 506, Generation: 5, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Herdier", SpeciesID: 507, Generation: 5, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Stoutland", SpeciesID: 508, Generation: 5, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Purrloin", SpeciesID: 509, Generation: 5, PokemonType: "PokemonType-Dark"),
                new PokemonModel(Name: "Liepard", SpeciesID: 510, Generation: 5, PokemonType: "PokemonType-Dark"),
                new PokemonModel(Name: "Pansage", SpeciesID: 511, Generation: 5, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Simisage", SpeciesID: 512, Generation: 5, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Pansear", SpeciesID: 513, Generation: 5, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Simisear", SpeciesID: 514, Generation: 5, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Panpour", SpeciesID: 515, Generation: 5, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Simipour", SpeciesID: 516, Generation: 5, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Munna", SpeciesID: 517, Generation: 5, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Musharna", SpeciesID: 518, Generation: 5, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Pidove", SpeciesID: 519, Generation: 5, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Tranquill", SpeciesID: 520, Generation: 5, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Unfezant", SpeciesID: 521, Generation: 5, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Blitzle", SpeciesID: 522, Generation: 5, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Zebstrika", SpeciesID: 523, Generation: 5, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Roggenrola", SpeciesID: 524, Generation: 5, PokemonType: "PokemonType-Rock"),
                new PokemonModel(Name: "Boldore", SpeciesID: 525, Generation: 5, PokemonType: "PokemonType-Rock"),
                new PokemonModel(Name: "Gigalith", SpeciesID: 526, Generation: 5, PokemonType: "PokemonType-Rock"),
                new PokemonModel(Name: "Woobat", SpeciesID: 527, Generation: 5, PokemonType: "PokemonType-Flying, PokemonType-Psychic"),
                new PokemonModel(Name: "Swoobat", SpeciesID: 528, Generation: 5, PokemonType: "PokemonType-Flying, PokemonType-Psychic"),
                new PokemonModel(Name: "Drilbur", SpeciesID: 529, Generation: 5, PokemonType: "PokemonType-Ground"),
                new PokemonModel(Name: "Excadrill", SpeciesID: 530, Generation: 5, PokemonType: "PokemonType-Ground, PokemonType-Steel"),
                new PokemonModel(Name: "Audino", SpeciesID: 531, Generation: 5, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Timburr", SpeciesID: 532, Generation: 5, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Gurdurr", SpeciesID: 533, Generation: 5, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Conkeldurr", SpeciesID: 534, Generation: 5, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Tympole", SpeciesID: 535, Generation: 5, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Palpitoad", SpeciesID: 536, Generation: 5, PokemonType: "PokemonType-Ground, PokemonType-Water"),
                new PokemonModel(Name: "Seismitoad", SpeciesID: 537, Generation: 5, PokemonType: "PokemonType-Ground, PokemonType-Water"),
                new PokemonModel(Name: "Throh", SpeciesID: 538, Generation: 5, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Sawk", SpeciesID: 539, Generation: 5, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Sewaddle", SpeciesID: 540, Generation: 5, PokemonType: "PokemonType-Bug, PokemonType-Grass"),
                new PokemonModel(Name: "Swadloon", SpeciesID: 541, Generation: 5, PokemonType: "PokemonType-Bug, PokemonType-Grass"),
                new PokemonModel(Name: "Leavanny", SpeciesID: 542, Generation: 5, PokemonType: "PokemonType-Bug, PokemonType-Grass"),
                new PokemonModel(Name: "Venipede", SpeciesID: 543, Generation: 5, PokemonType: "PokemonType-Poison, PokemonType-Bug"),
                new PokemonModel(Name: "Whirlipede", SpeciesID: 544, Generation: 5, PokemonType: "PokemonType-Poison, PokemonType-Bug"),
                new PokemonModel(Name: "Scolipede", SpeciesID: 545, Generation: 5, PokemonType: "PokemonType-Poison, PokemonType-Bug"),
                new PokemonModel(Name: "Cottonee", SpeciesID: 546, Generation: 5, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Whimsicott", SpeciesID: 547, Generation: 5, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Petilil", SpeciesID: 548, Generation: 5, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Lilligant", SpeciesID: 549, Generation: 5, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Basculin-red-striped", SpeciesID: 550, Generation: 5, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Sandile", SpeciesID: 551, Generation: 5, PokemonType: "PokemonType-Ground, PokemonType-Dark"),
                new PokemonModel(Name: "Krokorok", SpeciesID: 552, Generation: 5, PokemonType: "PokemonType-Ground, PokemonType-Dark"),
                new PokemonModel(Name: "Krookodile", SpeciesID: 553, Generation: 5, PokemonType: "PokemonType-Ground, PokemonType-Dark"),
                new PokemonModel(Name: "Darumaka", SpeciesID: 554, Generation: 5, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Darmanitan-standard", SpeciesID: 555, Generation: 5, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Maractus", SpeciesID: 556, Generation: 5, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Dwebble", SpeciesID: 557, Generation: 5, PokemonType: "PokemonType-Rock, PokemonType-Bug"),
                new PokemonModel(Name: "Crustle", SpeciesID: 558, Generation: 5, PokemonType: "PokemonType-Rock, PokemonType-Bug"),
                new PokemonModel(Name: "Scraggy", SpeciesID: 559, Generation: 5, PokemonType: "PokemonType-Fighting, PokemonType-Dark"),
                new PokemonModel(Name: "Scrafty", SpeciesID: 560, Generation: 5, PokemonType: "PokemonType-Fighting, PokemonType-Dark"),
                new PokemonModel(Name: "Sigilyph", SpeciesID: 561, Generation: 5, PokemonType: "PokemonType-Flying, PokemonType-Psychic"),
                new PokemonModel(Name: "Yamask", SpeciesID: 562, Generation: 5, PokemonType: "PokemonType-Ghost"),
                new PokemonModel(Name: "Cofagrigus", SpeciesID: 563, Generation: 5, PokemonType: "PokemonType-Ghost"),
                new PokemonModel(Name: "Tirtouga", SpeciesID: 564, Generation: 5, PokemonType: "PokemonType-Rock, PokemonType-Water"),
                new PokemonModel(Name: "Carracosta", SpeciesID: 565, Generation: 5, PokemonType: "PokemonType-Rock, PokemonType-Water"),
                new PokemonModel(Name: "Archen", SpeciesID: 566, Generation: 5, PokemonType: "PokemonType-Flying, PokemonType-Rock"),
                new PokemonModel(Name: "Archeops", SpeciesID: 567, Generation: 5, PokemonType: "PokemonType-Flying, PokemonType-Rock"),
                new PokemonModel(Name: "Trubbish", SpeciesID: 568, Generation: 5, PokemonType: "PokemonType-Poison"),
                new PokemonModel(Name: "Garbodor", SpeciesID: 569, Generation: 5, PokemonType: "PokemonType-Poison"),
                new PokemonModel(Name: "Zorua", SpeciesID: 570, Generation: 5, PokemonType: "PokemonType-Dark"),
                new PokemonModel(Name: "Zoroark", SpeciesID: 571, Generation: 5, PokemonType: "PokemonType-Dark"),
                new PokemonModel(Name: "Minccino", SpeciesID: 572, Generation: 5, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Cinccino", SpeciesID: 573, Generation: 5, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Gothita", SpeciesID: 574, Generation: 5, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Gothorita", SpeciesID: 575, Generation: 5, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Gothitelle", SpeciesID: 576, Generation: 5, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Solosis", SpeciesID: 577, Generation: 5, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Duosion", SpeciesID: 578, Generation: 5, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Reuniclus", SpeciesID: 579, Generation: 5, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Ducklett", SpeciesID: 580, Generation: 5, PokemonType: "PokemonType-Flying, PokemonType-Water"),
                new PokemonModel(Name: "Swanna", SpeciesID: 581, Generation: 5, PokemonType: "PokemonType-Flying, PokemonType-Water"),
                new PokemonModel(Name: "Vanillite", SpeciesID: 582, Generation: 5, PokemonType: "PokemonType-Ice"),
                new PokemonModel(Name: "Vanillish", SpeciesID: 583, Generation: 5, PokemonType: "PokemonType-Ice"),
                new PokemonModel(Name: "Vanilluxe", SpeciesID: 584, Generation: 5, PokemonType: "PokemonType-Ice"),
                new PokemonModel(Name: "Deerling", SpeciesID: 585, Generation: 5, PokemonType: "PokemonType-Normal, PokemonType-Grass"),
                new PokemonModel(Name: "Sawsbuck", SpeciesID: 586, Generation: 5, PokemonType: "PokemonType-Normal, PokemonType-Grass"),
                new PokemonModel(Name: "Emolga", SpeciesID: 587, Generation: 5, PokemonType: "PokemonType-Flying, PokemonType-Electric"),
                new PokemonModel(Name: "Karrablast", SpeciesID: 588, Generation: 5, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Escavalier", SpeciesID: 589, Generation: 5, PokemonType: "PokemonType-Bug, PokemonType-Steel"),
                new PokemonModel(Name: "Foongus", SpeciesID: 590, Generation: 5, PokemonType: "PokemonType-Poison, PokemonType-Grass"),
                new PokemonModel(Name: "Amoonguss", SpeciesID: 591, Generation: 5, PokemonType: "PokemonType-Poison, PokemonType-Grass"),
                new PokemonModel(Name: "Frillish", SpeciesID: 592, Generation: 5, PokemonType: "PokemonType-Ghost, PokemonType-Water"),
                new PokemonModel(Name: "Jellicent", SpeciesID: 593, Generation: 5, PokemonType: "PokemonType-Ghost, PokemonType-Water"),
                new PokemonModel(Name: "Alomomola", SpeciesID: 594, Generation: 5, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Joltik", SpeciesID: 595, Generation: 5, PokemonType: "PokemonType-Bug, PokemonType-Electric"),
                new PokemonModel(Name: "Galvantula", SpeciesID: 596, Generation: 5, PokemonType: "PokemonType-Bug, PokemonType-Electric"),
                new PokemonModel(Name: "Ferroseed", SpeciesID: 597, Generation: 5, PokemonType: "PokemonType-Steel, PokemonType-Grass"),
                new PokemonModel(Name: "Ferrothorn", SpeciesID: 598, Generation: 5, PokemonType: "PokemonType-Steel, PokemonType-Grass"),
                new PokemonModel(Name: "Klink", SpeciesID: 599, Generation: 5, PokemonType: "PokemonType-Steel"),
                new PokemonModel(Name: "Klang", SpeciesID: 600, Generation: 5, PokemonType: "PokemonType-Steel"),
                new PokemonModel(Name: "Klinklang", SpeciesID: 601, Generation: 5, PokemonType: "PokemonType-Steel"),
                new PokemonModel(Name: "Tynamo", SpeciesID: 602, Generation: 5, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Eelektrik", SpeciesID: 603, Generation: 5, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Eelektross", SpeciesID: 604, Generation: 5, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Elgyem", SpeciesID: 605, Generation: 5, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Beheeyem", SpeciesID: 606, Generation: 5, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Litwick", SpeciesID: 607, Generation: 5, PokemonType: "PokemonType-Ghost, PokemonType-Fire"),
                new PokemonModel(Name: "Lampent", SpeciesID: 608, Generation: 5, PokemonType: "PokemonType-Ghost, PokemonType-Fire"),
                new PokemonModel(Name: "Chandelure", SpeciesID: 609, Generation: 5, PokemonType: "PokemonType-Ghost, PokemonType-Fire"),
                new PokemonModel(Name: "Axew", SpeciesID: 610, Generation: 5, PokemonType: "PokemonType-Dragon"),
                new PokemonModel(Name: "Fraxure", SpeciesID: 611, Generation: 5, PokemonType: "PokemonType-Dragon"),
                new PokemonModel(Name: "Haxorus", SpeciesID: 612, Generation: 5, PokemonType: "PokemonType-Dragon"),
                new PokemonModel(Name: "Cubchoo", SpeciesID: 613, Generation: 5, PokemonType: "PokemonType-Ice"),
                new PokemonModel(Name: "Beartic", SpeciesID: 614, Generation: 5, PokemonType: "PokemonType-Ice"),
                new PokemonModel(Name: "Cryogonal", SpeciesID: 615, Generation: 5, PokemonType: "PokemonType-Ice"),
                new PokemonModel(Name: "Shelmet", SpeciesID: 616, Generation: 5, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Accelgor", SpeciesID: 617, Generation: 5, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Stunfisk", SpeciesID: 618, Generation: 5, PokemonType: "PokemonType-Ground, PokemonType-Electric"),
                new PokemonModel(Name: "Mienfoo", SpeciesID: 619, Generation: 5, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Mienshao", SpeciesID: 620, Generation: 5, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Druddigon", SpeciesID: 621, Generation: 5, PokemonType: "PokemonType-Dragon"),
                new PokemonModel(Name: "Golett", SpeciesID: 622, Generation: 5, PokemonType: "PokemonType-Ground, PokemonType-Ghost"),
                new PokemonModel(Name: "Golurk", SpeciesID: 623, Generation: 5, PokemonType: "PokemonType-Ground, PokemonType-Ghost"),
                new PokemonModel(Name: "Pawniard", SpeciesID: 624, Generation: 5, PokemonType: "PokemonType-Steel, PokemonType-Dark"),
                new PokemonModel(Name: "Bisharp", SpeciesID: 625, Generation: 5, PokemonType: "PokemonType-Steel, PokemonType-Dark"),
                new PokemonModel(Name: "Bouffalant", SpeciesID: 626, Generation: 5, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Rufflet", SpeciesID: 627, Generation: 5, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Braviary", SpeciesID: 628, Generation: 5, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Vullaby", SpeciesID: 629, Generation: 5, PokemonType: "PokemonType-Flying, PokemonType-Dark"),
                new PokemonModel(Name: "Mandibuzz", SpeciesID: 630, Generation: 5, PokemonType: "PokemonType-Flying, PokemonType-Dark"),
                new PokemonModel(Name: "Heatmor", SpeciesID: 631, Generation: 5, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Durant", SpeciesID: 632, Generation: 5, PokemonType: "PokemonType-Bug, PokemonType-Steel"),
                new PokemonModel(Name: "Deino", SpeciesID: 633, Generation: 5, PokemonType: "PokemonType-Dragon, PokemonType-Dark"),
                new PokemonModel(Name: "Zweilous", SpeciesID: 634, Generation: 5, PokemonType: "PokemonType-Dragon, PokemonType-Dark"),
                new PokemonModel(Name: "Hydreigon", SpeciesID: 635, Generation: 5, PokemonType: "PokemonType-Dragon, PokemonType-Dark"),
                new PokemonModel(Name: "Larvesta", SpeciesID: 636, Generation: 5, PokemonType: "PokemonType-Bug, PokemonType-Fire"),
                new PokemonModel(Name: "Volcarona", SpeciesID: 637, Generation: 5, PokemonType: "PokemonType-Bug, PokemonType-Fire"),
                new PokemonModel(Name: "Cobalion", SpeciesID: 638, Generation: 5, PokemonType: "PokemonType-Fighting, PokemonType-Steel"),
                new PokemonModel(Name: "Terrakion", SpeciesID: 639, Generation: 5, PokemonType: "PokemonType-Fighting, PokemonType-Rock"),
                new PokemonModel(Name: "Virizion", SpeciesID: 640, Generation: 5, PokemonType: "PokemonType-Fighting, PokemonType-Grass"),
                new PokemonModel(Name: "Tornadus-incarnate", SpeciesID: 641, Generation: 5, PokemonType: "PokemonType-Flying"),
                new PokemonModel(Name: "Thundurus-incarnate", SpeciesID: 642, Generation: 5, PokemonType: "PokemonType-Flying, PokemonType-Electric"),
                new PokemonModel(Name: "Reshiram", SpeciesID: 643, Generation: 5, PokemonType: "PokemonType-Fire, PokemonType-Dragon"),
                new PokemonModel(Name: "Zekrom", SpeciesID: 644, Generation: 5, PokemonType: "PokemonType-Electric, PokemonType-Dragon"),
                new PokemonModel(Name: "Landorus-incarnate", SpeciesID: 645, Generation: 5, PokemonType: "PokemonType-Flying, PokemonType-Ground"),
                new PokemonModel(Name: "Kyurem", SpeciesID: 646, Generation: 5, PokemonType: "PokemonType-Ice, PokemonType-Dragon"),
                new PokemonModel(Name: "Keldeo-ordinary", SpeciesID: 647, Generation: 5, PokemonType: "PokemonType-Fighting, PokemonType-Water"),
                new PokemonModel(Name: "Meloetta-aria", SpeciesID: 648, Generation: 5, PokemonType: "PokemonType-Normal, PokemonType-Psychic"),
                new PokemonModel(Name: "Genesect", SpeciesID: 649, Generation: 5, PokemonType: "PokemonType-Bug, PokemonType-Steel"),
                new PokemonModel(Name: "Chespin", SpeciesID: 650, Generation: 6, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Quilladin", SpeciesID: 651, Generation: 6, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Chesnaught", SpeciesID: 652, Generation: 6, PokemonType: "PokemonType-Fighting, PokemonType-Grass"),
                new PokemonModel(Name: "Fennekin", SpeciesID: 653, Generation: 6, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Braixen", SpeciesID: 654, Generation: 6, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Delphox", SpeciesID: 655, Generation: 6, PokemonType: "PokemonType-Fire, PokemonType-Psychic"),
                new PokemonModel(Name: "Froakie", SpeciesID: 656, Generation: 6, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Frogadier", SpeciesID: 657, Generation: 6, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Greninja", SpeciesID: 658, Generation: 6, PokemonType: "PokemonType-Water, PokemonType-Dark"),
                new PokemonModel(Name: "Bunnelby", SpeciesID: 659, Generation: 6, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Diggersby", SpeciesID: 660, Generation: 6, PokemonType: "PokemonType-Normal, PokemonType-Ground"),
                new PokemonModel(Name: "Fletchling", SpeciesID: 661, Generation: 6, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Fletchinder", SpeciesID: 662, Generation: 6, PokemonType: "PokemonType-Flying, PokemonType-Fire"),
                new PokemonModel(Name: "Talonflame", SpeciesID: 663, Generation: 6, PokemonType: "PokemonType-Flying, PokemonType-Fire"),
                new PokemonModel(Name: "Scatterbug", SpeciesID: 664, Generation: 6, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Spewpa", SpeciesID: 665, Generation: 6, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Vivillon", SpeciesID: 666, Generation: 6, PokemonType: "PokemonType-Flying, PokemonType-Bug"),
                new PokemonModel(Name: "Litleo", SpeciesID: 667, Generation: 6, PokemonType: "PokemonType-Normal, PokemonType-Fire"),
                new PokemonModel(Name: "Pyroar", SpeciesID: 668, Generation: 6, PokemonType: "PokemonType-Normal, PokemonType-Fire"),
                new PokemonModel(Name: "Skiddo", SpeciesID: 672, Generation: 6, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Gogoat", SpeciesID: 673, Generation: 6, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Pancham", SpeciesID: 674, Generation: 6, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Pangoro", SpeciesID: 675, Generation: 6, PokemonType: "PokemonType-Fighting, PokemonType-Dark"),
                new PokemonModel(Name: "Furfrou", SpeciesID: 676, Generation: 6, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Espurr", SpeciesID: 677, Generation: 6, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Meowstic-male", SpeciesID: 678, Generation: 6, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Honedge", SpeciesID: 679, Generation: 6, PokemonType: "PokemonType-Ghost, PokemonType-Steel"),
                new PokemonModel(Name: "Doublade", SpeciesID: 680, Generation: 6, PokemonType: "PokemonType-Ghost, PokemonType-Steel"),
                new PokemonModel(Name: "Aegislash-shield", SpeciesID: 681, Generation: 6, PokemonType: "PokemonType-Ghost, PokemonType-Steel"),
                new PokemonModel(Name: "Inkay", SpeciesID: 686, Generation: 6, PokemonType: "PokemonType-Psychic, PokemonType-Dark"),
                new PokemonModel(Name: "Malamar", SpeciesID: 687, Generation: 6, PokemonType: "PokemonType-Psychic, PokemonType-Dark"),
                new PokemonModel(Name: "Binacle", SpeciesID: 688, Generation: 6, PokemonType: "PokemonType-Rock, PokemonType-Water"),
                new PokemonModel(Name: "Barbaracle", SpeciesID: 689, Generation: 6, PokemonType: "PokemonType-Rock, PokemonType-Water"),
                new PokemonModel(Name: "Skrelp", SpeciesID: 690, Generation: 6, PokemonType: "PokemonType-Poison, PokemonType-Water"),
                new PokemonModel(Name: "Dragalge", SpeciesID: 691, Generation: 6, PokemonType: "PokemonType-Poison, PokemonType-Dragon"),
                new PokemonModel(Name: "Clauncher", SpeciesID: 692, Generation: 6, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Clawitzer", SpeciesID: 693, Generation: 6, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Helioptile", SpeciesID: 694, Generation: 6, PokemonType: "PokemonType-Normal, PokemonType-Electric"),
                new PokemonModel(Name: "Heliolisk", SpeciesID: 695, Generation: 6, PokemonType: "PokemonType-Normal, PokemonType-Electric"),
                new PokemonModel(Name: "Tyrunt", SpeciesID: 696, Generation: 6, PokemonType: "PokemonType-Rock, PokemonType-Dragon"),
                new PokemonModel(Name: "Tyrantrum", SpeciesID: 697, Generation: 6, PokemonType: "PokemonType-Rock, PokemonType-Dragon"),
                new PokemonModel(Name: "Amaura", SpeciesID: 698, Generation: 6, PokemonType: "PokemonType-Rock, PokemonType-Ice"),
                new PokemonModel(Name: "Aurorus", SpeciesID: 699, Generation: 6, PokemonType: "PokemonType-Rock, PokemonType-Ice"),
                new PokemonModel(Name: "Hawlucha", SpeciesID: 701, Generation: 6, PokemonType: "PokemonType-Fighting, PokemonType-Flying"),
                new PokemonModel(Name: "Dedenne", SpeciesID: 702, Generation: 6, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Carbink", SpeciesID: 703, Generation: 6, PokemonType: "PokemonType-Rock"),
                new PokemonModel(Name: "Goomy", SpeciesID: 704, Generation: 6, PokemonType: "PokemonType-Dragon"),
                new PokemonModel(Name: "Sliggoo", SpeciesID: 705, Generation: 6, PokemonType: "PokemonType-Dragon"),
                new PokemonModel(Name: "Goodra", SpeciesID: 706, Generation: 6, PokemonType: "PokemonType-Dragon"),
                new PokemonModel(Name: "Klefki", SpeciesID: 707, Generation: 6, PokemonType: "PokemonType-Steel"),
                new PokemonModel(Name: "Phantump", SpeciesID: 708, Generation: 6, PokemonType: "PokemonType-Ghost, PokemonType-Grass"),
                new PokemonModel(Name: "Trevenant", SpeciesID: 709, Generation: 6, PokemonType: "PokemonType-Ghost, PokemonType-Grass"),
                new PokemonModel(Name: "Pumpkaboo-average", SpeciesID: 710, Generation: 6, PokemonType: "PokemonType-Ghost, PokemonType-Grass"),
                new PokemonModel(Name: "Gourgeist-average", SpeciesID: 711, Generation: 6, PokemonType: "PokemonType-Ghost, PokemonType-Grass"),
                new PokemonModel(Name: "Bergmite", SpeciesID: 712, Generation: 6, PokemonType: "PokemonType-Ice"),
                new PokemonModel(Name: "Avalugg", SpeciesID: 713, Generation: 6, PokemonType: "PokemonType-Ice"),
                new PokemonModel(Name: "Noibat", SpeciesID: 714, Generation: 6, PokemonType: "PokemonType-Flying, PokemonType-Dragon"),
                new PokemonModel(Name: "Noivern", SpeciesID: 715, Generation: 6, PokemonType: "PokemonType-Flying, PokemonType-Dragon"),
                new PokemonModel(Name: "Yveltal", SpeciesID: 717, Generation: 6, PokemonType: "PokemonType-Flying, PokemonType-Dark"),
                new PokemonModel(Name: "Zygarde", SpeciesID: 718, Generation: 6, PokemonType: "PokemonType-Ground, PokemonType-Dragon"),
                new PokemonModel(Name: "Diancie", SpeciesID: 719, Generation: 6, PokemonType: "PokemonType-Rock"),
                new PokemonModel(Name: "Hoopa", SpeciesID: 720, Generation: 6, PokemonType: "PokemonType-Ghost, PokemonType-Psychic"),
                new PokemonModel(Name: "Volcanion", SpeciesID: 721, Generation: 6, PokemonType: "PokemonType-Fire, PokemonType-Water"),
                new PokemonModel(Name: "Rowlet", SpeciesID: 722, Generation: 7, PokemonType: "PokemonType-Flying, PokemonType-Grass"),
                new PokemonModel(Name: "Dartrix", SpeciesID: 723, Generation: 7, PokemonType: "PokemonType-Flying, PokemonType-Grass"),
                new PokemonModel(Name: "Decidueye", SpeciesID: 724, Generation: 7, PokemonType: "PokemonType-Ghost, PokemonType-Grass"),
                new PokemonModel(Name: "Litten", SpeciesID: 725, Generation: 7, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Torracat", SpeciesID: 726, Generation: 7, PokemonType: "PokemonType-Fire"),
                new PokemonModel(Name: "Incineroar", SpeciesID: 727, Generation: 7, PokemonType: "PokemonType-Fire, PokemonType-Dark"),
                new PokemonModel(Name: "Popplio", SpeciesID: 728, Generation: 7, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Brionne", SpeciesID: 729, Generation: 7, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Primarina", SpeciesID: 730, Generation: 7, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Pikipek", SpeciesID: 731, Generation: 7, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Trumbeak", SpeciesID: 732, Generation: 7, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Toucannon", SpeciesID: 733, Generation: 7, PokemonType: "PokemonType-Normal, PokemonType-Flying"),
                new PokemonModel(Name: "Yungoos", SpeciesID: 734, Generation: 7, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Gumshoos", SpeciesID: 735, Generation: 7, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Grubbin", SpeciesID: 736, Generation: 7, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Charjabug", SpeciesID: 737, Generation: 7, PokemonType: "PokemonType-Bug, PokemonType-Electric"),
                new PokemonModel(Name: "Vikavolt", SpeciesID: 738, Generation: 7, PokemonType: "PokemonType-Bug, PokemonType-Electric"),
                new PokemonModel(Name: "Crabrawler", SpeciesID: 739, Generation: 7, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Crabominable", SpeciesID: 740, Generation: 7, PokemonType: "PokemonType-Fighting, PokemonType-Ice"),
                new PokemonModel(Name: "Oricorio-baile", SpeciesID: 741, Generation: 7, PokemonType: "PokemonType-Flying, PokemonType-Fire"),
                new PokemonModel(Name: "Cutiefly", SpeciesID: 742, Generation: 7, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Ribombee", SpeciesID: 743, Generation: 7, PokemonType: "PokemonType-Bug"),
                new PokemonModel(Name: "Rockruff", SpeciesID: 744, Generation: 7, PokemonType: "PokemonType-Rock"),
                new PokemonModel(Name: "Lycanroc-midday", SpeciesID: 745, Generation: 7, PokemonType: "PokemonType-Rock"),
                new PokemonModel(Name: "Wishiwashi-solo", SpeciesID: 746, Generation: 7, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Mareanie", SpeciesID: 747, Generation: 7, PokemonType: "PokemonType-Poison, PokemonType-Water"),
                new PokemonModel(Name: "Toxapex", SpeciesID: 748, Generation: 7, PokemonType: "PokemonType-Poison, PokemonType-Water"),
                new PokemonModel(Name: "Mudbray", SpeciesID: 749, Generation: 7, PokemonType: "PokemonType-Ground"),
                new PokemonModel(Name: "Mudsdale", SpeciesID: 750, Generation: 7, PokemonType: "PokemonType-Ground"),
                new PokemonModel(Name: "Dewpider", SpeciesID: 751, Generation: 7, PokemonType: "PokemonType-Bug, PokemonType-Water"),
                new PokemonModel(Name: "Araquanid", SpeciesID: 752, Generation: 7, PokemonType: "PokemonType-Bug, PokemonType-Water"),
                new PokemonModel(Name: "Fomantis", SpeciesID: 753, Generation: 7, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Lurantis", SpeciesID: 754, Generation: 7, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Morelull", SpeciesID: 755, Generation: 7, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Shiinotic", SpeciesID: 756, Generation: 7, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Salandit", SpeciesID: 757, Generation: 7, PokemonType: "PokemonType-Poison, PokemonType-Fire"),
                new PokemonModel(Name: "Salazzle", SpeciesID: 758, Generation: 7, PokemonType: "PokemonType-Poison, PokemonType-Fire"),
                new PokemonModel(Name: "Stufful", SpeciesID: 759, Generation: 7, PokemonType: "PokemonType-Normal, PokemonType-Fighting"),
                new PokemonModel(Name: "Bewear", SpeciesID: 760, Generation: 7, PokemonType: "PokemonType-Normal, PokemonType-Fighting"),
                new PokemonModel(Name: "Bounsweet", SpeciesID: 761, Generation: 7, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Steenee", SpeciesID: 762, Generation: 7, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Tsareena", SpeciesID: 763, Generation: 7, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Oranguru", SpeciesID: 765, Generation: 7, PokemonType: "PokemonType-Normal, PokemonType-Psychic"),
                new PokemonModel(Name: "Passimian", SpeciesID: 766, Generation: 7, PokemonType: "PokemonType-Fighting"),
                new PokemonModel(Name: "Wimpod", SpeciesID: 767, Generation: 7, PokemonType: "PokemonType-Bug, PokemonType-Water"),
                new PokemonModel(Name: "Golisopod", SpeciesID: 768, Generation: 7, PokemonType: "PokemonType-Bug, PokemonType-Water"),
                new PokemonModel(Name: "Sandygast", SpeciesID: 769, Generation: 7, PokemonType: "PokemonType-Ground, PokemonType-Ghost"),
                new PokemonModel(Name: "Palossand", SpeciesID: 770, Generation: 7, PokemonType: "PokemonType-Ground, PokemonType-Ghost"),
                new PokemonModel(Name: "Pyukumuku", SpeciesID: 771, Generation: 7, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Type-null", SpeciesID: 772, Generation: 7, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Silvally", SpeciesID: 773, Generation: 7, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Minior-red-meteor", SpeciesID: 774, Generation: 7, PokemonType: "PokemonType-Flying, PokemonType-Rock"),
                new PokemonModel(Name: "Komala", SpeciesID: 775, Generation: 7, PokemonType: "PokemonType-Normal"),
                new PokemonModel(Name: "Turtonator", SpeciesID: 776, Generation: 7, PokemonType: "PokemonType-Fire, PokemonType-Dragon"),
                new PokemonModel(Name: "Togedemaru", SpeciesID: 777, Generation: 7, PokemonType: "PokemonType-Steel, PokemonType-Electric"),
                new PokemonModel(Name: "Mimikyu-disguised", SpeciesID: 778, Generation: 7, PokemonType: "PokemonType-Ghost"),
                new PokemonModel(Name: "Bruxish", SpeciesID: 779, Generation: 7, PokemonType: "PokemonType-Water, PokemonType-Psychic"),
                new PokemonModel(Name: "Drampa", SpeciesID: 780, Generation: 7, PokemonType: "PokemonType-Normal, PokemonType-Dragon"),
                new PokemonModel(Name: "Dhelmise", SpeciesID: 781, Generation: 7, PokemonType: "PokemonType-Ghost, PokemonType-Grass"),
                new PokemonModel(Name: "Jangmo-o", SpeciesID: 782, Generation: 7, PokemonType: "PokemonType-Dragon"),
                new PokemonModel(Name: "Hakamo-o", SpeciesID: 783, Generation: 7, PokemonType: "PokemonType-Fighting, PokemonType-Dragon"),
                new PokemonModel(Name: "Kommo-o", SpeciesID: 784, Generation: 7, PokemonType: "PokemonType-Fighting, PokemonType-Dragon"),
                new PokemonModel(Name: "Tapu-koko", SpeciesID: 785, Generation: 7, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Tapu-lele", SpeciesID: 786, Generation: 7, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Tapu-bulu", SpeciesID: 787, Generation: 7, PokemonType: "PokemonType-Grass"),
                new PokemonModel(Name: "Tapu-fini", SpeciesID: 788, Generation: 7, PokemonType: "PokemonType-Water"),
                new PokemonModel(Name: "Cosmog", SpeciesID: 789, Generation: 7, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Cosmoem", SpeciesID: 790, Generation: 7, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Solgaleo", SpeciesID: 791, Generation: 7, PokemonType: "PokemonType-Steel, PokemonType-Psychic"),
                new PokemonModel(Name: "Lunala", SpeciesID: 792, Generation: 7, PokemonType: "PokemonType-Ghost, PokemonType-Psychic"),
                new PokemonModel(Name: "Nihilego", SpeciesID: 793, Generation: 7, PokemonType: "PokemonType-Poison, PokemonType-Rock"),
                new PokemonModel(Name: "Buzzwole", SpeciesID: 794, Generation: 7, PokemonType: "PokemonType-Fighting, PokemonType-Bug"),
                new PokemonModel(Name: "Pheromosa", SpeciesID: 795, Generation: 7, PokemonType: "PokemonType-Fighting, PokemonType-Bug"),
                new PokemonModel(Name: "Xurkitree", SpeciesID: 796, Generation: 7, PokemonType: "PokemonType-Electric"),
                new PokemonModel(Name: "Celesteela", SpeciesID: 797, Generation: 7, PokemonType: "PokemonType-Flying, PokemonType-Steel"),
                new PokemonModel(Name: "Kartana", SpeciesID: 798, Generation: 7, PokemonType: "PokemonType-Steel, PokemonType-Grass"),
                new PokemonModel(Name: "Guzzlord", SpeciesID: 799, Generation: 7, PokemonType: "PokemonType-Dragon, PokemonType-Dark"),
                new PokemonModel(Name: "Necrozma", SpeciesID: 800, Generation: 7, PokemonType: "PokemonType-Psychic"),
                new PokemonModel(Name: "Magearna", SpeciesID: 801, Generation: 7, PokemonType: "PokemonType-Steel"),
                new PokemonModel(Name: "Marshadow", SpeciesID: 802, Generation: 7, PokemonType: "PokemonType-Fighting, PokemonType-Ghost"),
                new PokemonModel(Name: "Poipole", SpeciesID: 803, Generation: 7, PokemonType: "PokemonType-Poison"),
                new PokemonModel(Name: "Naganadel", SpeciesID: 804, Generation: 7, PokemonType: "PokemonType-Poison, PokemonType-Dragon"),
                new PokemonModel(Name: "Stakataka", SpeciesID: 805, Generation: 7, PokemonType: "PokemonType-Rock, PokemonType-Steel"),
                new PokemonModel(Name: "Blacephalon", SpeciesID: 806, Generation: 7, PokemonType: "PokemonType-Ghost, PokemonType-Fire"),
                new PokemonModel(Name: "Zeraora", SpeciesID: 807, Generation: 7, PokemonType: "PokemonType-Electric")
            };
            return lstPokemon;
        }
    }
}